#!/usr/bin/env bash
#
# install.sh — install the `wcup` launcher for the World Cup terminal dashboard.
#
# Drops a tiny launcher script on your PATH that runs this repo's wc.py.
# No dependencies, no pip, nothing copied into system directories.
#
#   ./install.sh                     # installs to ~/.local/bin
#   PREFIX=/usr/local/bin ./install.sh   # or pick your own bin dir
#
set -euo pipefail

# Resolve the directory this script lives in (portable; no readlink -f needed).
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${PREFIX:-$HOME/.local/bin}"

bold() { printf '\033[1m%s\033[0m\n' "$1"; }
ok()   { printf '\033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '\033[33m⚠\033[0m %s\n' "$1"; }
die()  { printf '\033[31m✗\033[0m %s\n' "$1" >&2; exit 1; }

bold "Installing wcup — FIFA World Cup 2026 terminal dashboard"

# --- locate a suitable python3 ---
PY="$(command -v python3 || true)"
[ -n "$PY" ] || die "Python 3 is required, but 'python3' was not found on your PATH."
"$PY" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 7) else 1)' \
  || die "Python 3.7+ is required (found $("$PY" -V 2>&1))."

echo "  repo:   $REPO_DIR"
echo "  python: $PY ($("$PY" -V 2>&1))"
echo "  target: $BIN_DIR/wcup"

# --- write the launcher ---
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/wcup" <<EOF
#!/bin/sh
# wcup — FIFA World Cup terminal dashboard  (generated by install.sh)
exec "$PY" "$REPO_DIR/wc.py" "\$@"
EOF
chmod +x "$BIN_DIR/wcup"
ok "installed launcher → $BIN_DIR/wcup"

# --- PATH check ---
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    warn "$BIN_DIR is not on your PATH. Add it, then restart your shell:"
    case "${SHELL##*/}" in
      zsh)  echo "    echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc" ;;
      bash) echo "    echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.bashrc" ;;
      *)    echo "    export PATH=\"$BIN_DIR:\$PATH\"   # add to your shell rc" ;;
    esac
    ;;
esac

echo
bold "Done. Try it:"
echo "    wcup              # live scores"
echo "    wcup --ENG        # a nation's page (any code; wcup --teams to list)"
echo "    wcup --help"
echo
echo "Already had a terminal open? Run 'hash -r' so the shell finds wcup."
